# .github/workflows/apiproxy-deploy.yml

name: Deploy ApiProxy

on:
  push:
    paths:
      - 'apiproxy.yaml'  # Trigger workflow only on changes to this file

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Read details from the config file
      - name: Read ApiProxy Details
        run: |
          API_NAME=$(yq .proxy apiproxy.yaml)
          REVISION=$(yq .revision apiproxy.yaml)
          TARGET_ENV=$(yq .env apiproxy.yaml)
          # ... (optional: extract kvm, targetName, targetUrl if needed)

      
      # Build the deployment URL dynamically
      - name: Build Deployment URL
        run: |
          DEPLOY_URL="https://api.enterprise.apigee.com/v1/organizations/zebra-prod/environments/$TARGET_ENV/apis/$API_NAME/revisions/$REVISION/deployments"

      # Deploy the API Proxy using curl (replace with your actual script)
      - name: Deploy ApiProxy
        run: |
          curl --request POST \"$DEPLOY_URL" \--header "Authorization: ${{ secrets.BEARER_TOKEN }}" \--header 'Accept: application/json' \--compressed

     
