# .github/workflows/apiproxy-deploy.yml

name: Deploy ApiProxy

on:
  push:
    paths:
      - 'apiproxy.yaml'  # Trigger workflow only on changes to this file

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Read details from the config file
      - name: Read ApiProxy Details
        run: |
          API_NAME=$(yq e '.proxy' apiproxy.yaml)
          REVISION=$(yq e '.revision' apiproxy.yaml)
          TARGET_ENV=$(yq e '.env' apiproxy.yaml)
          

      
      # Build the deployment URL dynamically
      - name: Build Deployment URL
        run: |
          DEPLOY_URL="https://api.enterprise.apigee.com/v1/organizations/zebra-prod/environments/$TARGET_ENV/apis/$API_NAME/revisions/$REVISION/deployments"
          
      # Deploy the API Proxy using curl
      - name: Deploy ApiProxy
        run: |
          curl --request POST "$DEPLOY_URL" \
            --header "Authorization: Bearer ${{ secrets.BEARER_TOKEN }}" \
            --header 'Accept: application/json' \
            --compressed
