name: Deploy ApiProxy

on:
  push:
    paths:
      - 'apiproxy.yaml'  # This workflow triggers on changes to the apiproxy.yaml file

jobs:
  deploy:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v3
        # Checks out your repository under $GITHUB_WORKSPACE, so our job can access it

      - name: Install yq
        # Installs yq to parse YAML files. 
        run: sudo snap install yq

      - name: Read ApiProxy Details
        
        run: |
          API_NAME=$(yq e '.proxy' apiproxy.yaml)
          REVISION=$(yq e '.revision' apiproxy.yaml)
          TARGET_ENV=$(yq e '.env' apiproxy.yaml)
          echo "API_NAME=${API_NAME}" >> $GITHUB_ENV
          echo "REVISION=${REVISION}" >> $GITHUB_ENV
          echo "TARGET_ENV=${TARGET_ENV}" >> $GITHUB_ENV
          
      - name: Build Deployment URL
        
        run: |
          DEPLOY_URL="https://api.enterprise.apigee.com/v1/organizations/zebra-prod/environments/$TARGET_ENV/apis/$API_NAME/revisions/$REVISION/deployments"
          echo "DEPLOY_URL=${DEPLOY_URL}" >> $GITHUB_ENV

      - name: Deploy ApiProxy
        
        run: |
          curl --request POST "$DEPLOY_URL" \
            --header "Authorization: Bearer ${{ secrets.BEARER_TOKEN }}" \
            --header 'Accept: application/json' \
            --compressed
