name: Deploy Proxy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load configuration file
        id: load_config
        run: |
          CONFIG=$(cat deploy_config.json)
          echo "Configuration: $CONFIG"
          echo "::set-output name=config::$CONFIG"

      - name: Deploy Proxy
        run: |
          CONFIG="${{ steps.load_config.outputs.config }}"
          PROXY_NAME=$(echo "$CONFIG" | jq -r '.proxy')
          REVISION=$(echo "$CONFIG" | jq -r '.revision')
          ENVIRONMENT=$(echo "$CONFIG" | jq -r '.env')
          ORGANIZATION="zebra-prod"  # Replace 'your_organization_name' with the actual organization name

          curl -X POST \
            -H "Content-Type: application/json" \
            -d "{\"override\": true}" \
            "https://api.enterprise.apigee.com/v1/organizations/${ORGANIZATION}/environments/${ENVIRONMENT}/apis/${PROXY_NAME}/revisions/${REVISION}/deployments"
