# .github/workflows/export-proxy.yml

name: Export Proxy

on:
  push:
    paths:
      - 'apiproxy.yaml'  # Trigger workflow on changes to apiproxy.yaml
  pull_request:
    paths:
      - 'apiproxy.yaml'  # Trigger workflow when a pull request modifies apiproxy.yaml

jobs:
  export_proxy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read Proxy Details
        run: |
          API_NAME=$(yq e '.proxy' apiproxy.yaml)
          REVISION=$(yq e '.revision' apiproxy.yaml)
          echo "API_NAME=${API_NAME}" >> $GITHUB_ENV
          echo "REVISION=${REVISION}" >> $GITHUB_ENV

      - name: Export Proxy
        run: |
          # Export the API proxy revision as a zip file
          curl -o proxy-config.zip \
            "https://api.enterprise.apigee.com/v1/organizations/{org_name}/apis/${API_NAME}/revisions/${REVISION}?format=bundle" \
            --header "Authorization: Bearer ${{ secrets.BEARER_TOKEN }}"

          # Upload the exported proxy as an artifact
          echo "##[group]Exported Proxy"
          echo "Exported proxy configuration for API: $API_NAME, Revision: $REVISION"
          echo "##[endgroup]"
          echo "Uploading proxy-config.zip as artifact..."
          echo "::set-output name=proxy-zip::proxy-config.zip"
          echo "::set-output name=proxy-name::$API_NAME"
          echo "::set-output name=proxy-revision::$REVISION"
          echo "::set-output name=artifact_path::proxy-config.zip"
          echo "::add-path::proxy-config.zip"

      - name: Upload Proxy Artifact
        uses: actions/upload-artifact@v2
        with:
          name: proxy-artifact
          path: ${{ steps.export_proxy.outputs.artifact_path }}
